version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: business-extractor-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: business_extractor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - business-extractor-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: business-extractor-pgadmin
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - business-extractor-network

volumes:
  postgres_data:

networks:
  business-extractor-network:
    driver: bridge 